version: '3.8'

services:
  wordpress:
    environment:
      - WORDPRESS_DEBUG=1
    ports:
      - "9000:9000"

  mysql:
    ports:
      - "33060:3306"

  nginx:
    ports:
      - "8080:80"

  redis:
    ports:
      - "63790:6379" 